### ISSUE TITLE
When creating an aspect using an apostrophe <'> sometimes sends the cursor to the start of the text box.

### ISSUE THREAD

**Issue by AlexKersjes** [fariapp/fari#83] opened 2020-07-08 13:55 UTC
## 🚩 Describe the bug

...

## 🔢 Steps to reproduce

...

## 🟢 Expected behavior

...

## 🔴 Actual behavior

...

## 💅 Screenshots

...

## 🖥 Desktop or Smartphone

- Browser: [e.g. chrome, safari]

## 📄 Additional context

...

**Comment by RPDeshaies** [comment] 2020-07-08 18:54
Hey,

Could you please fill out the necessary information inside this issue because without steps to reproduce it's quite hard for me to understand what is happening.

I've been trying to reproduce it without success.

**Comment by RPDeshaies** [comment] 2020-07-15 16:50
Closing issue has I haven't received additional info. Will re-open if needed

**Closed by RPDeshaies** 2020-07-15 16:50 UTC
Labels: bug, on hold
